### ISSUE TITLE
你好 请问为什么我的node的报错

### ISSUE THREAD

**Issue by a1871239745** [kyrcha/ama#1]
Encrypted private OpenSSH key detected, but no passphrase given出现这个问题

**Comment by kyrcha** [comment]
?

**Comment by a1871239745** [comment]
???什么




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Kyriakos Chatzidimitriou"<notifications@github.com&gt;; 
发送时间: 2020年6月5日(星期五) 晚上8:17
收件人: "kyrcha/ama"<ama@noreply.github.com&gt;; 
抄送: "小邓"<1871239745@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [kyrcha/ama] 你好 请问为什么我的node的报错 (#1)





 
?
